# Generated by Django 2.0.1 on 2018-01-12 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodifyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('spotify_id', models.CharField(max_length=62, unique=True)),
                ('access_token', models.CharField(max_length=200, unique=True)),
                ('refresh_token', models.CharField(max_length=200, unique=True)),
                ('spotify_profile_url', models.URLField()),
                ('spotify_image', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
